name: Terraform

on:
  push:
    branches: [main]
    paths: [terraform/**]
  pull_request:
    branches: [main]
    paths: [terraform/**]

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  terraform:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::427064007577:role/data-extraction-github-actions
          aws-region: us-east-1

      - uses: hashicorp/setup-terraform@v3

      - name: Init
        run: terraform init
        working-directory: terraform

      - name: Plan
        run: terraform plan
        working-directory: terraform

      - name: Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve
        working-directory: terraform
